"""map order_id to booking model

Revision ID: 2df2cf61cdea
Revises: 54141a314a71
Create Date: 2025-12-22 18:08:46.122037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df2cf61cdea'
down_revision: Union[str, Sequence[str], None] = '54141a314a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'order_id')
    # ### end Alembic commands ###
