"""replaced user_id with order_id on seat_locks

Revision ID: 7454e7024e4c
Revises: 497741cd2e9c
Create Date: 2025-12-27 21:41:46.016438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7454e7024e4c'
down_revision: Union[str, Sequence[str], None] = '497741cd2e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('seat_locks', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seat_locks', 'orders', ['order_id'], ['id'])
    op.drop_column('seat_locks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat_locks', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'seat_locks', type_='foreignkey')
    op.drop_column('seat_locks', 'order_id')
    op.alter_column('bookings', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
